vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        peinture_image:
            uri_prefix: /upload/peinture
            upload_destination: '%kernel.project_dir%/public/upload/peinture'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
